
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  USER: 'USER',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const CompanyType = {
  SCHOOL: 'SCHOOL',
  BUSINESS: 'BUSINESS',
  STORE: 'STORE'
} as const

export type CompanyType = (typeof CompanyType)[keyof typeof CompanyType]


export const CompanyRole = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER'
} as const

export type CompanyRole = (typeof CompanyRole)[keyof typeof CompanyRole]


export const ItemStatus = {
  UNASSIGNED: 'UNASSIGNED',
  ASSIGNED: 'ASSIGNED',
  LOST: 'LOST',
  FOUND: 'FOUND'
} as const

export type ItemStatus = (typeof ItemStatus)[keyof typeof ItemStatus]
